import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} p-5 text-dark-grayish-blue max-w-screen-xl mx-auto`}
      >
        <Header />
        <main className="grid gap-y-10 md:gap-x-5 grid-cols-1 md:grid-cols-3">
          {children}
        </main>
      </body>
    </html>
  );
}
